# Generated by Django 2.0 on 2019-12-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
