# Generated by Django 2.0 on 2019-12-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=128)),
                ('b_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Authors')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
    ]
