# Generated by Django 2.0 on 2019-12-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191209_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='articles', to='article.Article'),
        ),
    ]
